export const TEAMS = [
  { id: 'man-utd',   name: 'Manchester United',  shortName: 'MUN', primaryColor: '#DA291C' },
  { id: 'tottenham', name: 'Tottenham Hotspur',   shortName: 'TOT', primaryColor: '#132257' },
  { id: 'arsenal',   name: 'Arsenal',             shortName: 'ARS', primaryColor: '#EF0107' },
  { id: 'liverpool', name: 'Liverpool',           shortName: 'LIV', primaryColor: '#C8102E' },
  { id: 'chelsea',   name: 'Chelsea',             shortName: 'CHE', primaryColor: '#034694' },
  { id: 'man-city',  name: 'Manchester City',     shortName: 'MCI', primaryColor: '#6CABDD' },
];

export const POSTS = [
  // ── p1: 카세미루 이별 오피셜 (debate / MUN) ─────────────────────
  {
    id: 'p1',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '카세미루,\n맨유와 이별 오피셜',
    summary: '첫 시즌과 마지막 시즌은 레전드급. 그 사이 2~3시즌이 문제다.',
    tweet: {
      author: 'Samuel Luckhurst',
      initials: 'SL',
      handle: '@samuelluckhurst',
      tier: 2,
      text: '카세미루는 경기 후 기자회견에 참석할 예정이었지만 결국 "너무 감정적"이라서 진행하지 못했습니다. 막대한 연봉을 받았지만 맨유에서의 시간 동안 분명히 헌신적이었고, 관중들과 진정한 유대감을 형성했습니다.',
      timeAgo: '11시간 전',
    },
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9V2M9drksopVGFPxNhAZxDOHMO8U0Pm5i3w&s',
    club: 'MUN',
    status: 'Official',
    hashtags: ['#카세미루', '#맨유', '#이별'],
    reactions: 3200,
    comments: 1890,
    bookmarks: 421,
    shares: 134,
    voteFor: 35,
    voteAgainst: 65,
    voteForLabel: '성공한 영입',
    voteAgainstLabel: '실패한 영입',
    participants: 1890,
    recentTrend: { pct: 5, direction: 'against', time: '30분' },
    debateQuestion: '카세미루 영입, 성공이었나 실패였나?',
    aiNarrative: '트로피도 들었고 마지막 시즌도 임팩트가 있었다. 하지만 가운데 2~3시즌의 성적과 연봉을 생각하면 의문이 남는다.',
    aiSummary: {
      for: ['첫 시즌 수비 안정감 확실', '리그컵 우승 기여', '마지막 시즌도 존재감 강했다', '팬들과의 유대감은 진짜였다'],
      against: ['중간 시즌 퍼포먼스 하락이 뼈아팠다', '연봉 대비 총 기여도 의문', '그 돈이면 더 좋은 선택 가능했다'],
    },
    argumentPoints: [
      { id: 'a1', text: '첫 시즌 + 마지막 시즌은 레전드급 퍼포먼스', stance: 'for', comments: 182 },
      { id: 'a2', text: '중간 시즌들이 너무 실망스러웠다', stance: 'against', comments: 241 },
      { id: 'a3', text: '눈물의 이별 — 팬과의 유대는 진짜였다', stance: 'neutral', comments: 92 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '2시간', text: '맨유 팬 입장에서는 그냥 실패다. 1억 쓰고 중간 3시즌 버렸잖아', likes: 723, stance: 'against' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '3시간', text: '첫 시즌은 진짜 좋았다. 리그컵 들었고. 문제는 그 이후였지', likes: 512, stance: 'for' },
      { id: 3, rank: '03', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '4시간', text: '감정적이라 기자회견 못 했다는 게 오히려 더 사람 같아 보임', likes: 389 },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '5시간', text: '이번 시즌 카세미루 없을 때 팀이 얼마나 흔들렸는지 봤잖아. 그게 다야', likes: 234, stance: 'for' },
    ],
  },

  // ── p7: 하베르츠 결승골 / 아스날 우승 (today_debate / ARS) ───────
  {
    id: 'p7',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '하베르츠 결승골,\n아스날 우승 가능?',
    summary: '번리전 1-0 승리로 우승 3점 차. 마지막 라운드에 모든 것이 걸렸다.',
    tweet: {
      author: 'Sky Sports Premier League',
      initials: 'SS',
      handle: '@SkySports',
      tier: 1,
      text: "FULL-TIME: Kai Havertz's strike seals the win, putting the Gunners within three points of the Premier League title! 🏆🔴",
      timeAgo: '8시간 전',
    },
    imageUrl: 'https://www.fbcnews.com.fj/wp-content/uploads/2024/10/harvez.jpg',
    club: 'ARS',
    status: 'Opinion',
    hashtags: ['#아스날', '#하베르츠', '#EPL우승'],
    reactions: 5600,
    comments: 3100,
    bookmarks: 789,
    shares: 445,
    voteFor: 54,
    voteAgainst: 46,
    voteForLabel: '우승 가능',
    voteAgainstLabel: '또 무너진다',
    participants: 3100,
    recentTrend: { pct: 4, direction: 'for', time: '30분' },
    debateQuestion: '아스날, 이번 시즌 마침내 우승할 수 있을까?',
    aiNarrative: '마지막 라운드, 단 3점 차. 하베르츠의 결승골로 희망을 이어갔다. 하지만 역사는 반복되는가 — 아스날은 또 무너질 것인가?',
    aiSummary: {
      for: ['현재 폼이 시즌 내내 최고 수준', '하베르츠의 결정력이 살아났다', '이번엔 다르다, 경험이 쌓였다'],
      against: ['마지막 라운드에서 아스날은 항상 무너진다', '선두는 3점 차 이상이 필요했다', '아르테타의 빅게임 운영이 여전히 걱정'],
    },
    argumentPoints: [
      { id: 'f1', text: '하베르츠, 이번 시즌 가장 중요한 골맨', stance: 'for', comments: 267 },
      { id: 'f2', text: '아스날은 타이틀 레이스마다 흔들렸다', stance: 'against', comments: 334 },
      { id: 'f3', text: '마지막 라운드 상대팀 일정이 관건', stance: 'neutral', comments: 198 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '1시간', text: '이번엔 진짜 된다. 하베르츠 폼 보라', likes: 1234, stance: 'for' },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '1시간', text: '16-17 이후 너무 오래됐다... 제발 이번엔', likes: 987, stance: 'for' },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', club: 'ARS', timeAgo: '2시간', text: '아스날 팬이지만 솔직히 마지막 라운드 믿음이 안 간다', likes: 756, stance: 'against' },
      { id: 4, rank: '04', initials: 'PL', user: '@prem_legacy', timeAgo: '2시간', text: '상대팀 일정 봐야지. 섣불리 판단 이르다', likes: 543 },
    ],
  },

  // ── p2: 칸셀루 바르사 잔류? (debate / MCI) ─────────────────────
  {
    id: 'p2',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '칸셀루, 바르사 잔류?\n사우디 복귀?',
    summary: '사우디에서 임대 온 칸셀루 — 플리크의 신임 vs 알 힐랄 복귀 압박.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: '한시 플리크, 칸셀루 잔류에 대해: "쉽지 않지만 데코가 처리 중입니다. 최근 경기에서 칸셀루가 우리에게 무엇을 줬는지 모두가 알고 있어요. 환상적인 선수입니다. 정말 많이 아낍니다."',
      timeAgo: '5시간 전',
    },
    imageUrl: 'https://www.fcbarcelona.com/fcbarcelona/photo/2023/09/25/08593578-2837-4af2-9235-e3a56e3db23c/2023-09-16_FCBvsBETIS_97.jpg',
    club: 'MCI',
    status: 'Talks',
    hashtags: ['#칸셀루', '#바르셀로나', '#사우디'],
    reactions: 2800,
    comments: 1540,
    bookmarks: 312,
    shares: 98,
    voteFor: 74,
    voteAgainst: 26,
    voteForLabel: '바르사 잔류',
    voteAgainstLabel: '사우디 복귀',
    participants: 1540,
    recentTrend: { pct: 6, direction: 'for', time: '1시간' },
    debateQuestion: '칸셀루, 바르사에 남아야 할까? 사우디로 돌아가야 할까?',
    aiNarrative: '알 힐랄에서 임대 온 칸셀루는 플리크 체제에서 완전히 살아났다. 하지만 바르사의 재정 불안과 알 힐랄의 복귀 요청이 걸림돌이다.',
    aiSummary: {
      for: ['플리크 체제에서 이번 시즌 커리어 최고폼', '바르셀로나 전술에 완벽히 최적화됨', '사우디 복귀는 커리어 사실상 종료'],
      against: ['알 힐랄 임대 계약 조건상 복귀 압박', '바르사 재정 불안 — 영구 계약은 불투명', '챔피언스리그 출전이 더 이상 보장 아님'],
    },
    argumentPoints: [
      { id: 'b1', text: '플리크 체제에서 커리어 최고폼 중', stance: 'for', comments: 198 },
      { id: 'b2', text: '사우디 복귀는 커리어 사실상 종료', stance: 'for', comments: 154 },
      { id: 'b3', text: '바르사 재정 불안 — 잔류 보장 없다', stance: 'against', comments: 211 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BF', user: '@barca_fan_kr', club: 'MCI', timeAgo: '1시간', text: '이번 시즌 칸셀루 없었으면 챔스 어땠을지... 무조건 잔류', likes: 634, stance: 'for' },
      { id: 2, rank: '02', initials: 'PL', user: '@prem_legacy', club: 'MCI', timeAgo: '2시간', text: '사우디 가면 커리어 끝나는 거다. 플리크 믿고 가야지', likes: 445, stance: 'for' },
      { id: 3, rank: '03', initials: 'FK', user: '@football_kr', club: 'MCI', timeAgo: '3시간', text: '알 힐랄이 복귀 원하는 이상 바르사가 돈 내야 하는데 과연 가능한가', likes: 267, stance: 'against' },
    ],
  },

  // ── p13: 야말 월드컵 첫경기 결장 (today_debate / ARS) ───────────
  {
    id: 'p13',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '야말, 월드컵 첫경기\n결장 가능성 제기',
    summary: '스페인의 핵심 야말이 컨디션 문제로 개막전 출전이 불투명해졌다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: "Lamine Yamal faces doubts over Spain's opening World Cup game. Knock suffered in training — medical team monitoring the situation closely. No decision yet.",
      timeAgo: '30분 전',
    },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Lamine_Yamal_in_2025.jpg',
    club: 'ARS',
    status: 'Opinion',
    hashtags: ['#야말', '#스페인', '#월드컵'],
    reactions: 4200,
    comments: 2700,
    bookmarks: 567,
    shares: 334,
    voteFor: 67,
    voteAgainst: 33,
    voteForLabel: '없어도 이긴다',
    voteAgainstLabel: '야말 필수',
    participants: 2700,
    recentTrend: { pct: 5, direction: 'for', time: '30분' },
    debateQuestion: '야말 없이 스페인 첫 경기, 승리할 수 있을까?',
    aiNarrative: '야말이 없어도 이기는 팀이라는 평가와, 야말이 없으면 스페인 공격의 창의성 자체가 사라진다는 우려가 팽팽히 맞선다.',
    aiSummary: {
      for: ['스페인 스쿼드 뎁스는 세계 최고 수준', '조별 첫 경기 상대 전력이 강하지 않다', '무리하지 않고 보호하는 게 장기적으로 맞다'],
      against: ['야말 없는 스페인 공격은 예측 불가능성을 잃는다', '유로 때처럼 야말이 바꾸는 판이 있다', '첫 경기 리듬이 토너먼트 전체에 영향'],
    },
    argumentPoints: [
      { id: 'y1', text: '페드리·모라타 있으면 첫 경기 충분히 이긴다', stance: 'for', comments: 312 },
      { id: 'y2', text: '야말의 드리블·돌파는 대체 불가', stance: 'against', comments: 289 },
      { id: 'y3', text: '첫경기 무리시키느니 2라운드부터 투입이 맞다', stance: 'neutral', comments: 201 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'SP', user: '@spain_kr', timeAgo: '15분', text: '스페인이 야말 하나 없다고 못 이기는 팀이냐. 뎁스가 얼만데', likes: 934, stance: 'for' },
      { id: 2, rank: '02', initials: 'BF', user: '@barca_fan_kr', timeAgo: '20분', text: '야말 없는 스페인 왼쪽은 진짜 다르다. 과소평가하지 마라', likes: 756, stance: 'against' },
      { id: 3, rank: '03', initials: 'WC', user: '@worldcup_kr', timeAgo: '25분', text: '첫경기 무리시키다가 다치면 어쩌려고. 그냥 2라운드부터 써라', likes: 612, stance: 'for' },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '30분', text: '유로 결승 야말 그 장면 생각하면... 제발 건강하게 나와줬으면', likes: 489 },
    ],
  },

  // ── p3: 브루노 20어시 달성 (today_debate / MUN) ─────────────────
  {
    id: 'p3',
    type: 'today_debate',
    badge: 'TODAY DEBATE',
    title: '브루노 20어시 달성,\n마지막 라운드 기록 경신?',
    summary: '앙리·데 브라이너와 EPL 역대 타이기록. 1라운드 남았다.',
    tweet: {
      author: 'Simon Stone',
      initials: 'SS',
      handle: '@sistoney67',
      tier: 2,
      text: '브루노 페르난데스: "19개가 됐을 때 생각이 들기 시작했어요. 티에리와 케빈 얘기를 하는 거잖아요 — EPL의 메인 이름들이죠. 21개가 되면 좋겠지만 안 돼도 괜찮아요. 20어시도 해본 적 없었으니까."',
      timeAgo: '1시간 전',
    },
    imageUrl: 'https://static.independent.co.uk/2026/05/17/14/2276701105..',
    club: 'MUN',
    status: 'Opinion',
    hashtags: ['#브루노', '#어시스트기록', '#EPL역사'],
    reactions: 4100,
    comments: 2890,
    bookmarks: 678,
    shares: 312,
    voteFor: 61,
    voteAgainst: 39,
    voteForLabel: '21어시 신기록',
    voteAgainstLabel: '20어시 마감',
    participants: 2890,
    recentTrend: { pct: 8, direction: 'for', time: '30분' },
    debateQuestion: '마지막 라운드, 브루노 21어시 신기록 달성 가능?',
    aiNarrative: '단 1라운드 남았다. 앙리·데 브라이너와 어깨를 나란히 한 브루노 — 역사를 다시 쓸 수 있을까?',
    aiSummary: {
      for: ['현재 폼이 시즌 내내 최고 수준 유지', '마지막 경기 강력한 동기부여 확실', '이미 심리적 장벽을 넘은 상태'],
      against: ['상대팀이 집중 견제할 게 뻔하다', '단 1경기에서 어시스트 보장 없음', '팀 전술적 필요에 따라 달라질 수도'],
    },
    argumentPoints: [
      { id: 'c1', text: '현재 폼이면 21어시 충분히 가능', stance: 'for', comments: 312 },
      { id: 'c2', text: '상대팀 집중 견제가 변수', stance: 'against', comments: 278 },
      { id: 'c3', text: '20어시 자체가 이미 역사적 기록', stance: 'neutral', comments: 145 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BK', user: '@brunokr_fan', club: 'MUN', timeAgo: '30분', text: '앙리급 시즌이다. 21개 간다', likes: 1023, stance: 'for' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_numbers', club: 'MUN', timeAgo: '45분', text: '상대팀이 집중 마크할 텐데... 쉽지 않다', likes: 756, stance: 'against' },
      { id: 3, rank: '03', initials: 'MF', user: '@midfield_kr', club: 'MUN', timeAgo: '1시간', text: '20어시도 역대급인데 21까지? 이 세대 최고의 미드필더', likes: 534, stance: 'for' },
      { id: 4, rank: '04', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '1시간', text: '이 선수 팔자고? 기록 보고도 매각설 나오면 진짜 ㅋㅋ', likes: 445 },
    ],
  },

  // ── p5: 네이마르 눈물의 월드컵 발탁 (debate / 중립) ─────────────
  {
    id: 'p5',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '네이마르, 눈물의\n월드컵 발탁',
    summary: '2년 넘는 부상 공백 끝에 안첼로티의 깜짝 호출. 간절히 원했던 무대에서의 마지막 도전.',
    tweet: {
      author: 'The Athletic | Football',
      initials: 'TA',
      handle: '@TheAthletic',
      tier: 1,
      text: "Neymar is going to the World Cup. Carlo Ancelotti has seen fit to include the 34-year-old in his Brazil squad for this summer's tournament. Brentford's Igor Thiago and Bournemouth's Rayan have also been selected — but there is no place for Chelsea's Joao Pedro.",
      timeAgo: '7시간 전',
    },
    imageUrl: 'https://images.ctfassets.net/3mv54pzvptwz/55YLwKPDnRXkqMBITRpWbC/0c2aefc04afa455c20e9ca0d209698e0/53174188191_42d4c831ae_o.jpg',
    status: 'Official',
    hashtags: ['#네이마르', '#브라질', '#월드컵'],
    reactions: 4800,
    comments: 3200,
    bookmarks: 620,
    shares: 289,
    voteFor: 31,
    voteAgainst: 69,
    voteForLabel: '네이마르 필요해',
    voteAgainstLabel: '세대교체해야',
    participants: 3200,
    recentTrend: { pct: 9, direction: 'against', time: '1시간' },
    debateQuestion: '2년의 공백을 딛고 돌아온 네이마르, 브라질 월드컵 엔트리에 포함되어야 할까?',
    aiNarrative: '2년 넘게 부상으로 사라졌던 34살이 안첼로티의 손에 이끌려 돌아왔다. 마지막 무대를 향한 간절함과, 주앙 페드로 같은 젊은 피를 원하는 여론이 충돌하고 있다.',
    aiSummary: {
      for: ['2년 공백을 이겨낸 것 자체가 이미 기적', '큰 무대 경험은 아직 아무도 못 따라온다', '안첼로티가 직접 폼을 확인하고 내린 결정'],
      against: ['주앙 페드로를 포함시켰어야 했다', '부상 재발 리스크가 너무 높다', '34살에 월드컵 강도를 버틸 수 있을지 의문'],
    },
    argumentPoints: [
      { id: 'n1', text: '2년 공백 극복 — 의지만큼은 역대급', stance: 'for', comments: 289 },
      { id: 'n2', text: '주앙 페드로 탈락은 납득 불가', stance: 'against', comments: 412 },
      { id: 'n3', text: '부상 재발 시 팀 전체에 리스크', stance: 'against', comments: 356 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'BR', user: '@brazil_kr', timeAgo: '2시간', text: '2년을 이겨내고 돌아왔다는 것 자체가 감동이지. 응원할 수밖에', likes: 892, stance: 'for' },
      { id: 2, rank: '02', initials: 'JK', user: '@joaopedro_fan', timeAgo: '3시간', text: '주앙 페드로 팬으로서 진짜 납득이 안 감. 첼시에서 활약 중인데', likes: 734, stance: 'against' },
      { id: 3, rank: '03', initials: 'WC', user: '@worldcup_kr', timeAgo: '4시간', text: '카타르도 부상으로 나갔잖아. 이번엔 제발 버텨줬으면', likes: 521, stance: 'for' },
      { id: 4, rank: '04', initials: 'FK', user: '@football_kr', timeAgo: '5시간', text: '진짜 마지막 무대라는 거 알고 있을 텐데... 눈물날 것 같다', likes: 412 },
    ],
  },

  // ── p14: 알론소 첼시 감독 오피셜 (debate / CHE) ─────────────────
  {
    id: 'p14',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '알론소, 첼시 감독\n오피셜 확정',
    summary: '레버쿠젠 불패 신화의 주인공이 스탬포드 브릿지로 온다. 4년 계약 완료.',
    imageUrl: 'https://images2.minutemediacdn.com/image/upload/c_crop,x_0,y_0,w_1919,h_1079/c_fill,w_720,ar_16:9,f_auto,q_auto,g_auto/images/voltaxMediaLibrary/mmsport/si/01krtk3v16vszp5dee2e.jpg',
    tweet: {
      author: 'David Ornstein',
      initials: 'DO',
      handle: '@David_Ornstein',
      tier: 1,
      text: '🚨 EXCLUSIVE: Agreement complete for Xabi Alonso to become Chelsea manager. 44yo Spaniard visited London early last week & accepted opportunity; 4yr contract now finalised - announcement imminent. Primary target throughout + wanted #CFC move @TheAthleticFC',
      timeAgo: '2일 전',
    },
    club: 'CHE',
    status: 'Official',
    hashtags: ['#알론소', '#첼시', '#신임감독'],
    reactions: 5100,
    comments: 3400,
    bookmarks: 712,
    shares: 389,
    voteFor: 58,
    voteAgainst: 42,
    voteForLabel: '성공한다',
    voteAgainstLabel: '실패한다',
    participants: 3400,
    recentTrend: { pct: 6, direction: 'for', time: '1시간' },
    debateQuestion: '알론소, 첼시에서도 레버쿠젠의 기적을 재현할 수 있을까?',
    aiNarrative: '레버쿠젠 불패 시즌으로 세계 최고 감독 반열에 오른 알론소. 하지만 레알 마드리드에서의 기대 이하 성과가 남긴 물음표와, 첼시 특유의 구단 문화가 변수로 떠오르고 있다.',
    aiSummary: {
      for: ['레버쿠젠 불패 시즌 — 전술 능력은 이미 세계 최고급 검증', '첼시 스쿼드 뎁스라면 전술 구현 충분히 가능', '4년 장기 계약 — 구단이 완전한 신뢰를 보냈다'],
      against: ['레알 마드리드에서의 성과가 기대에 미치지 못했다', '첼시는 감독을 갈아치우는 구단 문화로 유명하다', 'PL은 분데스리가와 강도 자체가 다르다'],
    },
    argumentPoints: [
      { id: 'xa1', text: '레버쿠젠 불패 — 전술 천재임은 이미 증명', stance: 'for', comments: 423 },
      { id: 'xa2', text: '레알 이후 커리어에 물음표가 남았다', stance: 'against', comments: 356 },
      { id: 'xa3', text: '첼시 구단주가 또 감독 자를 수도 있다', stance: 'against', comments: 289 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'CF', user: '@chelsea_fan_kr', club: 'CHE', timeAgo: '1시간', text: '레버쿠젠 때 봤잖아. 믿어보자. 이번엔 진짜 제대로 된 감독 왔다', likes: 1123, stance: 'for' },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_london', club: 'CHE', timeAgo: '1시간', text: '첼시가 감독 4시즌 내보낸 거 알론소도 알 텐데... 각오하고 온 거겠지', likes: 867, stance: 'against' },
      { id: 3, rank: '03', initials: 'EK', user: '@epl_kr', timeAgo: '2시간', text: '레알에서 흔들린 게 좀 걸린다. PL은 진짜 다른 리그인데', likes: 654, stance: 'against' },
      { id: 4, rank: '04', initials: 'PL', user: '@prem_legacy', timeAgo: '2시간', text: '4년 계약이 포인트다. 구단이 진짜 오래 가져가겠다는 신호', likes: 512, stance: 'for' },
    ],
  },

  // ── p4: 캐릭 맨유 감독 거피셜 (debate / MUN) ────────────────────
  {
    id: 'p4',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '캐릭 맨유 감독 거피셜,\n내년 시즌 성공할까?',
    summary: '레전드가 감독직에 도전한다. 경험 부족 우려 vs 클럽 DNA 적임자.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: 'Michael Carrick set to be named Manchester United head coach. Discussions ongoing with the board. Decision expected soon. Here We Go soon! 🔴',
      timeAgo: '3시간 전',
    },
    imageUrl: 'https://i2-prod.manchestereveningnews.co.uk/article33961719.ece/ALTERNATES/s1200f/0_GettyImages-2276137385.jpg',
    club: 'MUN',
    status: 'Advanced',
    hashtags: ['#캐릭', '#맨유감독', '#리빌딩'],
    reactions: 2900,
    comments: 2100,
    bookmarks: 445,
    shares: 167,
    voteFor: 44,
    voteAgainst: 56,
    voteForLabel: '성공 가능',
    voteAgainstLabel: '회의적',
    participants: 2100,
    recentTrend: { pct: 3, direction: 'against', time: '1시간' },
    debateQuestion: '캐릭 감독 체제, 내년 시즌 성공할 수 있을까?',
    aiNarrative: '클럽 레전드가 감독직에 오른다. 경험 부족을 우려하는 시각과, 맨유 DNA를 아는 적임자라는 기대가 충돌 중이다.',
    aiSummary: {
      for: ['맨유 클럽 문화를 누구보다 잘 이해', '선수들과의 유대관계 이미 형성됨', '미들즈브러 감독직 현장 경험 보유'],
      against: ['최고 수준 감독 경력 전무', '리빌딩 상황에선 검증된 감독 필요', '전술적 유연성 아직 검증 안 됨'],
    },
    argumentPoints: [
      { id: 'd1', text: '맨유 DNA를 아는 감독이 필요한 시점', stance: 'for', comments: 267 },
      { id: 'd2', text: '최고 수준 감독 경력이 전무하다', stance: 'against', comments: 334 },
      { id: 'd3', text: '이적시장 보강이 성패를 가른다', stance: 'neutral', comments: 189 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '30분', text: '레전드가 맡는 건 좋은데 지금이 타이밍이 맞나? 경험이 너무 부족해', likes: 834, stance: 'against' },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '1시간', text: '일단 믿어보자. 맨유를 누구보다 잘 아는 사람이잖아', likes: 567, stance: 'for' },
      { id: 3, rank: '03', initials: 'SA', user: '@sir_alex_', club: 'MUN', timeAgo: '1시간', text: '전술 스태프 잘 꾸리면 가능하다. 퍼거슨도 처음엔 의심받았음', likes: 412, stance: 'for' },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '2시간', text: '이적시장 뭘 데려오느냐에 달려있다. 감독 혼자서는 답 없음', likes: 298 },
    ],
  },

  // ── p6: 펩 과르디올라 맨시티 이별 (sentimental / MCI) ───────────
  {
    id: 'p6',
    type: 'sentimental',
    title: '펩 과르디올라,\n맨시티와 이별',
    summary: '9년간 6번의 리그 우승, 챔피언스리그 우승까지. 이제 시대가 끝난다.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: 'Pep Guardiola has informed Manchester City that he will leave the club this summer. Decision confirmed and official statement to follow as Pep will say goodbye to Man City fans very soon. Only one name to replace Pep: Enzo Maresca.',
      timeAgo: '6시간 전',
    },
    imageUrl: 'https://i2-prod.liverpool.com/article33969458.ece/ALTERNATES/s1023/0_GettyImages-2276556390.jpg',
    club: 'MCI',
    status: 'Official',
    hashtags: ['#펩과르디올라', '#맨시티', '#이별'],
    reactions: 12400,
    comments: 2890,
    bookmarks: 1890,
    shares: 789,
    gradientFrom: '#001a38',
    accentColor: '#6dc1e7',
    icon: '🔵',
    comments_data: [
      { id: 1, rank: '01', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '30분', text: '9년간 감사했습니다. 역사상 최고의 감독이었습니다', likes: 4231 },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_legacy', club: 'MCI', timeAgo: '45분', text: '제발 1년만 더... 마지막으로 챔스 한 번만', likes: 3456 },
      { id: 3, rank: '03', initials: 'GG', user: '@guardiola_way', club: 'MCI', timeAgo: '1시간', text: '펩 없는 맨시티는 상상이 안 된다. 한 시대가 진짜 끝났다', likes: 2891 },
      { id: 4, rank: '04', initials: 'EM', user: '@etihad_memories', club: 'MCI', timeAgo: '1시간', text: '마르체스카가 후임이라고? 펩 그림자가 너무 크다', likes: 1823 },
    ],
  },

  // ── p15: 아르테타 "본머스 팬" (general / ARS) ────────────────────
  {
    id: 'p15',
    type: 'general',
    title: '아르테타 "나는 본머스의\n팬이 될 것"',
    summary: '우승까지 단 한 경기. 맨시티를 막아줄 본머스에게 아르테타가 공개 응원 메시지를 보냈다.',
    tweet: {
      author: 'Sky Sports News',
      initials: 'SS',
      handle: '@SkySportsNews',
      tier: 1,
      text: '"I will be the biggest Bournemouth fan ever, I will be there in front of the TV" 📺\n\nMikel Arteta says he\'ll be tuning in for tonight\'s game, where Arsenal will be crowned champions if Man City fail to win 🏆',
      timeAgo: '27분 전',
    },
    imageUrl: 'https://external-preview.redd.it/every-word-from-artetas-post-chelsea-presser-v0-LojAaY1XjGgAi2q7hx0s_g_GDsJoTIr1vchJdEkSyGU.jpeg?auto=webp&s=f5f1dd7e77ba680e07c67ed1fa139f030ad4533d',
    club: 'ARS',
    status: 'Opinion',
    hashtags: ['#아르테타', '#아스날', '#우승'],
    reactions: 8900,
    comments: 1240,
    bookmarks: 567,
    shares: 445,
    comments_data: [
      { id: 1, rank: '01', initials: 'AG', user: '@arsenal_gooner', club: 'ARS', timeAgo: '5분', text: '아르테타 ㅋㅋㅋ 본머스 응원한다고 ㅋㅋ 제발 이번엔 진짜로', likes: 2341 },
      { id: 2, rank: '02', initials: 'GK', user: '@gooner_kr', club: 'ARS', timeAgo: '10분', text: '본머스야 제발... 아스날 팬 전체가 너희를 응원한다', likes: 1987 },
      { id: 3, rank: '03', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '15분', text: '걱정 마라. 맨시티가 알아서 이긴다 ㅋㅋ', likes: 1123 },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '20분', text: '이 발언 자체가 화제다. 아르테타도 긴장 많이 되는 거지', likes: 876 },
    ],
  },

  // ── p10: 마레스카 맨시티 차기 감독 (debate / MCI) ───────────────
  {
    id: 'p10',
    type: 'debate',
    badge: 'HOT DEBATE',
    title: '마레스카, 펩 후임으로\n맨시티 유력 감독 후보',
    summary: '펩 떠난 자리에 마레스카? 첼시를 챔스까지 이끈 전술가, 에티하드에서도 통할까.',
    tweet: {
      author: 'Fabrizio Romano',
      initials: 'FR',
      handle: '@FabrizioRomano',
      tier: 1,
      text: "Enzo Maresca is the leading candidate to become Manchester City's next head coach following Pep Guardiola's departure. Contacts ongoing. Man City are convinced he can continue the project.",
      timeAgo: '4시간 전',
    },
    imageUrl: 'https://i.namu.wiki/i/D8ly0WWiB7_sWgztlLCUVlc7xR51rD_4JKhSvo1XyuzlQQbXeR8OAJcUYuLf4Nuyun2INsx8Qc_kZf1Rvyr8eg.webp',
    club: 'MCI',
    status: 'Advanced',
    hashtags: ['#마레스카', '#맨시티', '#차기감독'],
    reactions: 2600,
    comments: 1780,
    bookmarks: 389,
    shares: 112,
    voteFor: 42,
    voteAgainst: 58,
    voteForLabel: '성공한다',
    voteAgainstLabel: '실패한다',
    participants: 1780,
    recentTrend: { pct: 7, direction: 'against', time: '1시간' },
    debateQuestion: '마레스카, 펩 없는 맨시티에서 성공할 수 있을까?',
    aiNarrative: '첼시에서 챔피언스리그까지 이끌며 전술적 능력을 증명한 마레스카. 하지만 펩의 그림자가 드리운 에티하드에서의 압박은 차원이 다르다.',
    aiSummary: {
      for: ['첼시 체제에서 전술 구현 능력 이미 증명', '맨시티 스쿼드 퀄리티가 워낙 높아 초반 완충 가능', '젊은 감독 특유의 적응력과 유연성'],
      against: ['펩 후임이라는 심리적 압박은 상상 이상', '챔스 우승 경험 없는 감독에게 맨시티 팬들은 냉정', '에티하드 드레싱룸 장악은 전혀 다른 문제'],
    },
    argumentPoints: [
      { id: 'm1', text: '첼시 챔스 준결승 진출 — 전술 능력 증명 완료', stance: 'for', comments: 245 },
      { id: 'm2', text: '펩 그림자가 너무 크다 — 누가 와도 힘들다', stance: 'against', comments: 312 },
      { id: 'm3', text: '스쿼드 퀄리티가 감독을 커버해줄 것', stance: 'neutral', comments: 178 },
    ],
    comments_data: [
      { id: 1, rank: '01', initials: 'MC', user: '@mcfc_forever', club: 'MCI', timeAgo: '1시간', text: '첼시에서 그 선수들로 챔스 간 거잖아. 능력은 있다', likes: 678, stance: 'for' },
      { id: 2, rank: '02', initials: 'BL', user: '@blue_legacy', club: 'MCI', timeAgo: '2시간', text: '펩 후임이면 누구든 지옥이다. 마레스카 불쌍하다', likes: 534, stance: 'against' },
      { id: 3, rank: '03', initials: 'EM', user: '@etihad_memories', club: 'MCI', timeAgo: '2시간', text: '이미 첼시에서 증명했잖아. 맨시티 스쿼드면 더 잘하겠지', likes: 389, stance: 'for' },
      { id: 4, rank: '04', initials: 'GG', user: '@guardiola_way', club: 'MCI', timeAgo: '3시간', text: '뭘 해도 "펩 같았으면..."이라는 말 들을 건데. 힘든 자리다', likes: 267 },
    ],
  },

  // ── p11: 무리뉴 래시포드 재결합 (general / MUN) ─────────────────
  {
    id: 'p11',
    type: 'general',
    title: '무리뉴, 래시포드\n재결합 원한다는 루머',
    summary: '바르사 임대 종료 후 거취 미정인 래시포드. 무리뉴가 손짓하고 있다.',
    tweet: {
      author: 'Ben Jacobs',
      initials: 'BJ',
      handle: '@JacobsBen',
      tier: 2,
      text: "José Mourinho is interested in reuniting with Marcus Rashford this summer. Fenerbahçe exploring a deal as Rashford's loan at Barcelona ends. Rashford's future remains open.",
      timeAgo: '3시간 전',
    },
    imageUrl: 'https://vstatic.vietnam.vn/vietnam/resource/IMAGE/2026/05/16/1778934497483_2084811_43691430_2560_1440.jpeg',
    club: 'MUN',
    status: 'Rumour',
    hashtags: ['#래시포드', '#무리뉴', '#페네르바체'],
    reactions: 2100,
    comments: 1340,
    bookmarks: 234,
    shares: 89,
    comments_data: [
      { id: 1, rank: '01', initials: 'RD', user: '@red_devil_kr', club: 'MUN', timeAgo: '40분', text: '맨유 팬으로서 그냥 다시는 못 볼 것 같다는 생각이 드는 게 슬프다', likes: 712 },
      { id: 2, rank: '02', initials: 'BF', user: '@barca_fan_kr', timeAgo: '1시간', text: '바르사도 연장 생각 없다던데. 그냥 터키 가는 거 아닌가', likes: 523 },
      { id: 3, rank: '03', initials: 'RM', user: '@realmadrid_kr', timeAgo: '1시간', text: '무리뉴 밑에서 다시 기회 받으면 살아날 수도 있지 않나', likes: 401 },
      { id: 4, rank: '04', initials: 'MK', user: '@mancunian_kr', club: 'MUN', timeAgo: '2시간', text: '맨유에서 저 꼴 보고도 무리뉴가 원한다고? 이해가 안 됨', likes: 334 },
    ],
  },

  // ── p12: PGMO 오심 인정 (general / MUN) ─────────────────────────
  {
    id: 'p12',
    type: 'general',
    title: 'PGMO, 맨유전 쿠냐 골\n음뵈모 핸드볼 오심 인정',
    summary: '노팅엄전 결정적 오심. PGMO가 공식 인정했지만 결과는 바뀌지 않는다.',
    tweet: {
      author: 'Manchester United',
      initials: 'MU',
      handle: '@ManUtd',
      tier: 1,
      text: "Manchester United can confirm that PGMOL has acknowledged a significant error in the Matheus Cunha goal in the match against Nottingham Forest. Mbemo's handball in the build-up should have been penalised.",
      timeAgo: '2시간 전',
    },
    imageUrl: 'https://www.sportschosun.com/article/html/2026/05/19/2026051901001094100072481_w.jpg',
    club: 'MUN',
    status: 'Official',
    hashtags: ['#오심', '#PGMO', '#맨유'],
    reactions: 3400,
    comments: 2100,
    bookmarks: 312,
    shares: 198,
    comments_data: [
      { id: 1, rank: '01', initials: 'RC', user: '@redcafe_88', club: 'MUN', timeAgo: '20분', text: '인정은 해주는데 결과는 안 바꿔줌 ㅋㅋㅋ 이게 무슨 의미가 있냐', likes: 1234 },
      { id: 2, rank: '02', initials: 'UT', user: '@utd_history', club: 'MUN', timeAgo: '35분', text: 'VAR 뭐하냐 진짜. 저게 핸드볼 못 잡으면 뭘 잡는 거냐', likes: 987 },
      { id: 3, rank: '03', initials: 'SA', user: '@sir_alex_', club: 'MUN', timeAgo: '45분', text: '맨유한테는 왜 이런 게 항상 이렇게 많냐. 음모론 아님 그냥 통계다', likes: 756 },
      { id: 4, rank: '04', initials: 'EK', user: '@epl_kr', timeAgo: '1시간', text: '인정하면 뭐하나. 승점은 안 돌려주잖아. 매번 이 패턴', likes: 589 },
    ],
  },
];
